/**
 * Normalize OpenAPI documents generated by Slingr so they can be consumed by
 * the MCP/OpenAPI adapter.
 *
 * This module contains only deterministic, app-independent transformations.
 * App-specific decisions (especially Action classification) belong in
 * actions.js + overrides.js.
 */

const HTTP_METHODS = new Set([
  "get",
  "put",
  "post",
  "delete",
  "patch",
  "options",
  "head",
  "trace",
]);

const FIND_MANY_PARAMS = [
  { $ref: "#/components/parameters/_size" },
  { $ref: "#/components/parameters/_offset" },
  { $ref: "#/components/parameters/_sortField" },
  { $ref: "#/components/parameters/_sortType" },
  { $ref: "#/components/parameters/_fields" },
];

const PARAM_DEFINITIONS = {
  _size: {
    name: "_size",
    in: "query",
    required: false,
    description: "Limits the number of records returned. Maximum is 1000.",
    schema: { type: "integer" },
  },
  _offset: {
    name: "_offset",
    in: "query",
    required: false,
    description: "The offset to start retrieving records. Can be an integer or a record ID to start after.",
    schema: { type: "string" },
  },
  _sortField: {
    name: "_sortField",
    in: "query",
    required: false,
    description: "The field used to sort the results.",
    schema: { type: "string" },
  },
  _sortType: {
    name: "_sortType",
    in: "query",
    required: false,
    description: "The order of the sorting (asc or desc).",
    schema: { type: "string", enum: ["asc", "desc"] },
  },
  _fields: {
    name: "_fields",
    in: "query",
    required: false,
    description: "Comma separated list of fields to include in the response.",
    schema: { type: "string" },
  },
};

export function normalizeOpenAPI(input) {
  assertObject(input, "OpenAPI document");

  // Do not mutate the fetched document. This makes the normalizer easier to
  // test and lets callers retain the original document for diagnostics.
  const openapi = structuredClone(input);
  const stats = {
    definitionsMigrated: false,
    refsFixed: 0,
    tokenParamsRemoved: 0,
    findManyPatched: 0,
  };

  ensureObject(openapi, "components");

  if (openapi.definitions) {
    openapi.components.schemas = {
      ...(openapi.components.schemas ?? {}),
      ...openapi.definitions,
    };
    delete openapi.definitions;
    stats.definitionsMigrated = true;
  }

  walk(openapi, (node) => {
    if (typeof node.$ref === "string" && node.$ref.startsWith("#/definitions/")) {
      node.$ref = node.$ref.replace("#/definitions/", "#/components/schemas/");
      stats.refsFixed += 1;
    }
  });

  ensureObject(openapi.components, "parameters");
  for (const [name, definition] of Object.entries(PARAM_DEFINITIONS)) {
    openapi.components.parameters[name] = definition;
  }

  for (const pathItem of Object.values(openapi.paths ?? {})) {
    if (!pathItem || typeof pathItem !== "object" || Array.isArray(pathItem)) {
      continue;
    }

    stats.tokenParamsRemoved += stripTokenHeader(pathItem);

    for (const [method, operation] of Object.entries(pathItem)) {
      if (!HTTP_METHODS.has(method.toLowerCase())) continue;
      if (!operation || typeof operation !== "object" || Array.isArray(operation)) continue;

      stats.tokenParamsRemoved += stripTokenHeader(operation);

      if (isFindMany(operation.operationId)) {
        operation.parameters ??= [];
        for (const param of FIND_MANY_PARAMS) {
          if (!hasParam(operation.parameters, param)) {
            operation.parameters.push(param);
          }
        }
        stats.findManyPatched += 1;
      }
    }
  }

  return { openapi, stats };
}

function isFindMany(operationId) {
  return typeof operationId === "string" && operationId.toLowerCase().includes("findmany");
}

function stripTokenHeader(container) {
  if (!Array.isArray(container.parameters)) return 0;

  const before = container.parameters.length;
  container.parameters = container.parameters.filter(
    (param) => !(param && param.in === "header" && param.name === "token"),
  );

  if (container.parameters.length === 0) {
    delete container.parameters;
  }

  return before - (container.parameters?.length ?? 0);
}

function hasParam(parameters, param) {
  return parameters.some((existing) => {
    if (param.$ref) return existing?.$ref === param.$ref;
    return existing?.name === param.name && existing?.in === param.in;
  });
}

function ensureObject(parent, key) {
  if (!parent[key] || typeof parent[key] !== "object" || Array.isArray(parent[key])) {
    parent[key] = {};
  }
}

function assertObject(value, name) {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError(`${name} must be an object.`);
  }
}

function walk(node, visitor) {
  if (Array.isArray(node)) {
    for (const child of node) walk(child, visitor);
    return;
  }

  if (node && typeof node === "object") {
    visitor(node);
    for (const value of Object.values(node)) walk(value, visitor);
  }
}
