/**
 * App-specific overrides.
 *
 * The OpenAPI generated by Slingr cannot always express all Builder semantics.
 * For example, a global Action may be documented as if it were record-scoped.
 * Overrides provide an explicit escape hatch without hard-coding a particular
 * Slingr App into the generic adapter.
 */

export function createOverrides(input = {}) {
  if (!input || typeof input !== "object" || Array.isArray(input)) {
    throw new TypeError("Overrides must be an object.");
  }

  return {
    actionMode: normalizeActionMode(input.actionMode),
    globalActions: normalizeStringList(input.globalActions),
    recordScopedActions: normalizeStringList(input.recordScopedActions),
    removePaths: normalizeStringList(input.removePaths),
  };
}

export function normalizeActionMode(value) {
  const mode = value ?? "blacklist";

  if (!["blacklist", "whitelist", "all"].includes(mode)) {
    throw new Error(
      `Invalid actionMode "${mode}". Expected "blacklist", "whitelist", or "all".`,
    );
  }

  return mode;
}

function normalizeStringList(value) {
  if (value == null) return [];
  if (!Array.isArray(value)) {
    throw new TypeError("Override lists must be arrays of strings.");
  }

  return [...new Set(
    value
      .map((item) => String(item).trim())
      .filter(Boolean),
  )];
}
